version: '3'

services:
  app:
    image: openjdk:21-jdk
    volumes:
      - ./src/main/java/com/example/datatuch:/app
    command: sh -c "while ! nc -z database 5432; do sleep 1; done && java -jar /app/DataTuch.jar"
    depends_on:
      - postgres
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1488
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
